### ISSUE TITLE
Scene上のPrefabの扱いを考える

### ISSUE THREAD

**Issue by negi0109** [negi0109/unity-history-viewer#9]
## 概要
Prefabの状態によってシリアライズの構造が大きく変わるため対策が必要
- Prefab Variant

### Prefabを配置しただけ
PrefabInstance型のオブジェクトが配置される
値を変更するまたは、コンポーネントの削除だけであればこの形で出力されそう。
GUIDから(?)prefabのパスを取得しprefabの取得を行わなければそれぞれの変更点の示すコンポーネントが分からない

```yaml
--- !u!1001 &4718096229195418463
PrefabInstance:
  m_ObjectHideFlags: 0
  serializedVersion: 2
  m_Modification:
    m_TransformParent: {fileID: 0}
    m_Modifications:
    - target: {fileID: 4718096228747403906, guid: d746955d1e397469a9e57173ef97bef7, type: 3}
      propertyPath: m_Name
      value: Main Camera 2
      objectReference: {fileID: 0}
```

### コンポーネントの追加を行った場合
分割される。 (idの後にstrippedがつくケースは想定していなかったため考慮が必要)
GameObjectやPrefabInstanceに追加されるコンポーネントの記述はない。
```yaml
--- !u!1 &534047197 stripped
GameObject:
  m_CorrespondingSourceObject: {fileID: 4718096228747403906, guid: d746955d1e397469a9e57173ef97bef7, type: 3}
  m_PrefabInstance: {fileID: 4718096229195418463}
  m_PrefabAsset: {fileID: 0}
--- !u!33 &534047201
MeshFilter:
  m_ObjectHideFlags: 0
  m_CorrespondingSourceObject: {fileID: 0}
  m_PrefabInstance: {fileID: 0}
  m_PrefabAsset: {fileID: 0}
  m_GameObject: {fileID: 534047197}
  m_Mesh: {fileID: 0}
PrefabInstance:
  ここから先は上のケースと同じ
...
```
#### 元のGameObjectに子GameObjectがあり、子GameObjectにコンポーネントを追加している場合
- .prefabファイルのyaml構造は通常のGameObjectと同様の構造
- prefabのGameObjectの構造
   Prefab1 (fileId: 4718096228747403906)
   |- test (fileId: 6578856811166717895)

子GameObjectに対応するstrippedなものがsceneには出力される。
```yaml
--- !u!1 &1508792863 stripped
GameObject:
  m_CorrespondingSourceObject: {fileID: 6578856811166717895, guid: d746955d1e397469a9e57173ef97bef7, type: 3}
  m_PrefabInstance: {fileID: 1508792860}
  m_PrefabAsset: {fileID: 0}
--- !u!61 &1508792864
BoxCollider2D:
  m_ObjectHideFlags: 0
  m_CorrespondingSourceObject: {fileID: 0}
  m_PrefabInstance: {fileID: 0}
  m_PrefabAsset: {fileID: 0}
  m_GameObject: {fileID: 1508792863}
  m_Enabled: 1
```
### GameObjectを追加した場合
- prefabのGameObjectの構造
   Prefab1 (fileId: 4718096228747403906) + transformのfileIDは4718096228747403906
- scene上の構造
  Prefab1を基にしたprefab
  |- add GameObject (fileId: 413748730)
元のtransformの実態はprefabにあるためstrippedなtransformが出力されている?
```yaml
--- !u!4 &1508792865 stripped
Transform:
  m_CorrespondingSourceObject: {fileID: 4718096228747403967, guid: d746955d1e397469a9e57173ef97bef7, type: 3}
  m_PrefabInstance: {fileID: 1508792860}
  m_PrefabAsset: {fileID: 0}
--- !u!4 &413748731
Transform:
  m_ObjectHideFlags: 0
  m_CorrespondingSourceObject: {fileID: 0}
  m_PrefabInstance: {fileID: 0}
  m_PrefabAsset: {fileID: 0}
  m_GameObject: {fileID: 413748730}
  m_Father: {fileID: 1508792865}
--- !u!1 &413748730
GameObject:
  m_CorrespondingSourceObject: {fileID: 0}
  m_Name: add GameObject
  m_PrefabInstance: {fileID: 0}
  m_PrefabAsset: {fileID: 0}
  serializedVersion: 6
  m_Component:
  - component: {fileID: 413748731}
```

### 参考に通常のGameObject
```yaml
--- !u!1 &519420028
GameObject:
  m_ObjectHideFlags: 0
  m_CorrespondingSourceObject: {fileID: 0}
  m_PrefabInstance: {fileID: 0}
  m_PrefabAsset: {fileID: 0}
  serializedVersion: 6
  m_Component:
  - component: {fileID: 519420032}
  - component: {fileID: 519420031}
  - component: {fileID: 519420029}
  m_Layer: 0
```

PrefabInstanceのfileIDとPrefab元のfileIDのXORをとるとScene上に置かれるStrippedなGameObjectのIDが算出できる。
(これでGameObjectからPrefab相互間で変換ができそう)
(コンポーネントにもこのルールが適応できるかは要調査、きっとできる)
